version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        command:
            - "sleep 5;"
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "1Secure*Password1"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        container_name: db

